version: '3.8'

services:
  backend:
    build: ./back
    container_name: sin_backend_ai
    ports:
      - "8001:8000"
    restart: always
    env_file:
      - .env

  frontend:
    build: ./front
    container_name: sin_frontend_ai
    ports:
      - "8502:8501"
    depends_on:
      - backend
    restart: always
